# Generated by Django 4.1.1 on 2022-09-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrMISApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizaion',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='organization address'),
        ),
    ]
