# Generated by Django 4.1.1 on 2022-09-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrMISApp', '0002_organizaion_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizaion',
            name='type',
            field=models.CharField(default='', max_length=200, verbose_name='organization type'),
        ),
    ]
