# Generated by Django 4.1.1 on 2022-09-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrMISApp', '0003_alter_country_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
