# Generated by Django 4.1.1 on 2022-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrMISApp', '0004_alter_country_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('published_year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
