# Generated by Django 4.1.1 on 2022-10-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrMISApp', '0005_choice_question_delete_employee_delete_organizaion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('pin_code', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
