# Generated by Django 4.1.1 on 2022-10-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrMISApp', '0005_choice_question_delete_employee_delete_organizaion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='TrMISApp.question'),
        ),
    ]
