# Generated by Django 4.1.1 on 2022-10-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(db_column='course_category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(db_column='course_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(db_column='course_category_id', on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory')),
            ],
        ),
    ]
