# Generated by Django 4.1.1 on 2022-10-17 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdate',
            name='currentdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 17, 7, 16, 6, 320686, tzinfo=datetime.timezone.utc)),
        ),
    ]
