# Generated by Django 4.1.1 on 2022-10-17 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_currentdate_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdate',
            name='currentdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 17, 7, 18, 22, 588925, tzinfo=datetime.timezone.utc)),
        ),
    ]
