# Generated by Django 4.1.1 on 2022-10-17 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_currentdate_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdate',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
