# Generated by Django 4.1.1 on 2022-10-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_currentdate_currentdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentDate',
        ),
    ]
