# Generated by Django 4.1.1 on 2022-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_delete_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='start_at',
            field=models.DateField(help_text="Enter the today's date"),
        ),
    ]
