# Generated by Django 4.1.1 on 2022-10-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_coursedetails_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='start_at',
            field=models.DateField(),
        ),
    ]
