# Generated by Django 4.1.1 on 2022-10-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_coursedetails_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
