# Generated by Django 4.1.1 on 2022-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursedetails_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='start_at',
            field=models.DateField(default='2022-12-13', help_text="Enter the today's date"),
        ),
    ]
