# Generated by Django 4.1.1 on 2022-10-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_coursedetails_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='start_at',
        ),
    ]
