# Generated by Django 4.1.1 on 2022-10-17 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_coursedetails_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='start_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
