# Generated by Django 4.1.1 on 2022-10-17 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_coursedetails_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='end_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Please enter end date'),
            preserve_default=False,
        ),
    ]
