# Generated by Django 4.1.1 on 2022-10-17 11:16

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_coursedetails_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='end_at',
            field=models.DateField(help_text='Please enter end date', validators=[courses.models.no_small_date]),
        ),
    ]
