# Generated by Django 4.1.1 on 2022-10-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplemodelquery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_for_sales', to='multiplemodelquery.appointment'),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
