# Generated by Django 4.1.1 on 2022-11-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
