# Generated by Django 4.1.1 on 2022-10-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date_time_Field', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date',
        ),
    ]
