# Generated by Django 4.1.1 on 2022-10-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_time_Field', '0002_remove_company_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_Date', models.DateField(help_text='Enter the date of purchase', max_length=10)),
            ],
        ),
    ]
