# Generated by Django 4.1.1 on 2022-10-17 08:56

import date_time_Field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_time_Field', '0003_member_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterField(
            model_name='member_registration',
            name='Purchase_Date',
            field=models.DateField(help_text='Enter the date of purchase', validators=[date_time_Field.models.no_future]),
        ),
    ]
